apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tcc
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'backend-java'
        static_configs:
          - targets: ['backend-java:8081']
        metrics_path: /actuator/prometheus

      - job_name: 'backend-go'
        static_configs:
          - targets: ['backend-go:8082']
        metrics_path: /metrics

      - job_name: 'backend-quarkus'
        static_configs:
          - targets: ['backend-quarkus:8083']
        metrics_path: /actuator/prometheus

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
